### PR TITLE
Remove is_ground_truth and is_detection properties

### PR DESCRIPTION
**Pull request by dsgibbons**
The current `BoundingBox` class has properties `is_ground_truth` and `is_detection` that are basically just aliases for `self.confidence is None` and `self.confidence is not None` respectively. Some models may not produce confidence scores, which then causes issues during `evaluate_boxes` in `evaluation.py`. I could add fake confidence values when creating the detection `AnnotationSet`, but I think it would be better to not mandate users to provide confidence values.

I have tested locally and everything passes. You may want to consider altering the GitHub action to automate tests on pull requests? I can open this up as a separate PR.

### CODE REVIEW

**Comment by laclouis5** [comment]
I'm looking into this one more closely since it would change the existing behavior and could potentially introduce subtle bugs. 

For instance the current behavior is to raise an error if the prediction bounding boxes do not have a confidence since it is probably a logic error from the user (e.g. it supplied a ground-truth set instead of the predictions one). The new behavior would not catch this error anymore. Maybe we could add a new optional `ignore_confidence` argument defaulting to `False` to `COCOEvaluator` to support your use case. 

**However, I wonder is this use case is very common. Do you have examples of object detectors that do not output confidence scores or is this just to support the use case where the user did not saved the scores?**

I also need to make sure that this does not break the reproducibility of the evaluation since this would makes the prediction bounding boxes order dependent.

**Comment by dsgibbons** [comment]
> However, I wonder is this use case is very common. Do you have examples of object detectors that do not output confidence scores or is this just to support the use case where the user did not saved the scores?

Some models don't provide confidences by default. For example, traditional (non-neural network) computer vision detectors (see for example, online tutorials [here ](https://pyimagesearch.com/2020/09/21/opencv-automatic-license-number-plate-recognition-anpr-with-python/) and [here](https://www.section.io/engineering-education/license-plate-detection-and-recognition-using-opencv-and-pytesseract/)). Some neural network architectures don't provide confidences either unless extra post processing is applied (e.g., [WPOD-NET](https://openaccess.thecvf.com/content_ECCV_2018/papers/Sergio_Silva_License_Plate_Detection_ECCV_2018_paper.pdf) for license plate detection). I imagine most users will be using more typical object detectors (e.g., YOLO, R-CNN etc.) where confidences are provided by default, but I think there would be enough demand for detectors that don't provide confidences.

> For instance the current behavior is to raise an error if the prediction bounding boxes do not have a confidence since it is probably a logic error from the user (e.g. it supplied a ground-truth set instead of the predictions one).

The `COCOEvaluator.__init__` uses mandatory keyword arguments via the * operator for ground truth and predictions `AnnotationSet`. We could look at expanding the use of mandatory keyword arguments to class methods such as `COCOEvaluator.evaluate_annotations` and `COCOEvaluator.evaluate_boxes` to minimise the chance of user error? Or maybe the underlying `AnnotationSet` should have a user-specified attribute for `is_ground_truth`, rather than using the presence of confidences as a proxy?

> I also need to make sure that this does not break the reproducibility of the evaluation since this would makes the prediction bounding boxes order dependent.

Agreed. I don't love my current implementation that currently assigns minimum confidence to no-confidence predictions:
```python
dets = sorted(predictions, key=lambda box: box._confidence if box._confidence is not None else -float("inf"), reverse=True)
```

I'm definitely open to exploring other solutions if you don't like the above behaviour.

**Comment by laclouis5** [comment]
So experimented with your implementation of the COCO evaluation without confidence scores and found that the metrics are dependent on the order of the bounding boxes. Here is a failing test case that illustrate this:

```python
def test_evaluator_no_confidence_invariance_to_bboxes_order():
    gts = AnnotationSet(annotations=[
        Annotation("img_1", image_size=(100, 100), boxes=[
            BoundingBox(label="cat", xmin=0, ymin=0, xmax=3, ymax=3),
            BoundingBox(label="cat", xmin=1, ymin=0, xmax=4, ymax=3),
        ])
    ])
    
    dets_1 = AnnotationSet(annotations=[
        Annotation("img_1", image_size=(100, 100), boxes=[
            BoundingBox(label="cat", xmin=-1, ymin=0, xmax=2, ymax=3),
            BoundingBox(label="cat", xmin=0, ymin=0, xmax=3, ymax=3),
        ])
    ])
    
    dets_2 = AnnotationSet(annotations=[
        Annotation("img_1", image_size=(100, 100), boxes=[
            BoundingBox(label="cat", xmin=0, ymin=0, xmax=3, ymax=3),
            BoundingBox(label="cat", xmin=-1, ymin=0, xmax=2, ymax=3),
        ])
    ])
    
    evaluator_1 = COCOEvaluator(ground_truths=gts, predictions=dets_1)
    ap_1 = evaluator_1.ap_50()
    
    evaluator_2 = COCOEvaluator(ground_truths=gts, predictions=dets_2)
    ap_2 = evaluator_2.ap_50()
    
    assert isclose(ap_1, ap_2)
```

Here, the only difference between `dets_1` and `dets_2` is the order of the two bounding boxes in the (unique) annotation. This ends up in producing different AP 50 (100% vs 50%).

In fact, COCO evaluation **requires** the ranking of bounding boxes with their confidence score, thus, this would be inappropriate to modify the current implementation in the proposed way.

I think that the most correct way to handle predictions without confidence score is the one you suggested: assigning "fake" confidence scores to the bounding boxes. In this case, the value does not matter (assuming that the same value is assigned to all bounding boxes) but I suggest a value of 1.0. Note that you'll still have to deal with the dependence of the metrics on the order of the bounding boxes. You could sort the bounding boxes according to an arbitrary value, for instance `xmin`, to deal with this issue.

**Comment by dsgibbons** [comment]
I see your point now. I didn't realise that the assignment between detection boxes and ground truth boxes was done by ordering the confidence values. I had previously assumed that this matching was done with a more global approach - something like a Hungarian algorithm to maximise average IOU. No worries, I'll close this PR :)

**Pull request closed without merging**
